# Complete working example for ESPHome with FauxmoESP
esphome:
  name: alexa-smart-home
  platform: ESP32
  board: esp32dev

# Use the external component from GitHub
external_components:
  - source: github://rajiteh/esphome-fauxmoesp
    components: [fauxmoesp]

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Static IP recommended for reliability
  manual_ip:
    static_ip: 192.168.1.100
    gateway: 192.168.1.1
    subnet: 255.255.255.0

# Enable logging
logger:
  level: DEBUG

# Enable Home Assistant API (optional)
api:

# Enable OTA updates
ota:

# Configure FauxmoESP component
fauxmoesp:
  port: 80 # REQUIRED for Gen3 Alexa devices
  enabled: true
  create_server: true

  devices:
    - name: "Living Room Light"
      id: living_room
      on_state:
        - logger.log:
            format: "Alexa commanded Living Room: %s (brightness: %d)"
            args: ['state ? "ON" : "OFF"', "value"]
        - if:
            condition:
              lambda: "return state;"
            then:
              - light.turn_on:
                  id: living_room_light
                  brightness: !lambda "return value / 255.0;"
            else:
              - light.turn_off: living_room_light

    - name: "Kitchen Light"
      id: kitchen
      on_state:
        - logger.log:
            format: "Alexa commanded Kitchen: %s (brightness: %d)"
            args: ['state ? "ON" : "OFF"', "value"]
        - if:
            condition:
              lambda: "return state;"
            then:
              - light.turn_on:
                  id: kitchen_light
                  brightness: !lambda "return value / 255.0;"
            else:
              - light.turn_off: kitchen_light

    - name: "Bedroom Fan"
      id: bedroom_fan
      on_state:
        - switch.turn_on: fan_switch
        - lambda: |-
            if (state) {
              id(fan_switch).turn_on();
            } else {
              id(fan_switch).turn_off();
            }

# Define your actual hardware outputs
output:
  - platform: ledc
    pin: GPIO23
    id: living_room_output

  - platform: ledc
    pin: GPIO22
    id: kitchen_output

# Define lights
light:
  - platform: monochromatic
    name: "Living Room Light"
    id: living_room_light
    output: living_room_output
    on_turn_on:
      # Sync state back to Alexa
      - lambda: |-
          auto brightness = id(living_room_light).remote_values.get_brightness();
          id(fauxmo_component).set_device_state("Living Room Light", true, brightness * 255);
    on_turn_off:
      - lambda: |-
          id(fauxmo_component).set_device_state("Living Room Light", false, 0);

  - platform: monochromatic
    name: "Kitchen Light"
    id: kitchen_light
    output: kitchen_output

# Define switches
switch:
  - platform: gpio
    pin: GPIO21
    name: "Fan Switch"
    id: fan_switch
    on_turn_on:
      - lambda: 'id(fauxmo_component).set_device_state("Bedroom Fan", true, 255);'
    on_turn_off:
      - lambda: 'id(fauxmo_component).set_device_state("Bedroom Fan", false, 0);'

# Reference the FauxmoESP component for programmatic access
globals:
  - id: fauxmo_component
    type: FauxmoESPComponent*
    initial_value: "nullptr"
