# Minimal configuration example
esphome:
  name: alexa-device
  platform: ESP8266
  board: nodemcuv2

external_components:
  - source:
      type: local
      path: components
    components: [fauxmoesp]

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

logger:

api:

ota:

# FauxmoESP - Port 80 required for Gen3 Alexa
fauxmoesp:
  port: 80
  devices:
    - name: "Smart Light"
      on_state:
        # Variables: device_name (string), state (bool)
        - logger.log:
            format: "%s: %s"
            args: ["device_name.c_str()", 'state ? "ON" : "OFF"']
        - if:
            condition:
              lambda: "return state;"
            then:
              - switch.turn_on: relay
            else:
              - switch.turn_off: relay

switch:
  - platform: gpio
    pin: GPIO5
    name: "Relay"
    id: relay
