# Complete working example for ESPHome with FauxmoESP (Subtixx fork)
esphome:
  name: alexa-smart-home
  platform: ESP32
  board: esp32dev

# Use the local external component
external_components:
  - source:
      type: local
      path: components
    components: [fauxmoesp]

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Static IP recommended for reliability
  manual_ip:
    static_ip: 192.168.1.100
    gateway: 192.168.1.1
    subnet: 255.255.255.0

logger:
  level: DEBUG

api:

ota:

# Configure FauxmoESP component
# Port 80 is REQUIRED for Gen3 Alexa devices
fauxmoesp:
  id: fauxmo_component
  port: 80
  enabled: true

  devices:
    - name: "Living Room Light"
      on_state:
        # Available variables: device_name (string), state (bool)
        - logger.log:
            format: "Alexa: %s turned %s"
            args: ['device_name.c_str()', 'state ? "ON" : "OFF"']
        - if:
            condition:
              lambda: "return state;"
            then:
              - light.turn_on: living_room_light
            else:
              - light.turn_off: living_room_light

    - name: "Kitchen Light"
      on_state:
        - if:
            condition:
              lambda: "return state;"
            then:
              - light.turn_on: kitchen_light
            else:
              - light.turn_off: kitchen_light

    - name: "Bedroom Fan"
      on_state:
        - if:
            condition:
              lambda: "return state;"
            then:
              - switch.turn_on: fan_switch
            else:
              - switch.turn_off: fan_switch

# Hardware outputs
output:
  - platform: ledc
    pin: GPIO23
    id: living_room_output

  - platform: ledc
    pin: GPIO22
    id: kitchen_output

# Lights
light:
  - platform: monochromatic
    name: "Living Room Light"
    id: living_room_light
    output: living_room_output
    on_turn_on:
      - lambda: 'id(fauxmo_component).set_device_state("Living Room Light", true);'
    on_turn_off:
      - lambda: 'id(fauxmo_component).set_device_state("Living Room Light", false);'

  - platform: monochromatic
    name: "Kitchen Light"
    id: kitchen_light
    output: kitchen_output
    on_turn_on:
      - lambda: 'id(fauxmo_component).set_device_state("Kitchen Light", true);'
    on_turn_off:
      - lambda: 'id(fauxmo_component).set_device_state("Kitchen Light", false);'

# Switches
switch:
  - platform: gpio
    pin: GPIO21
    name: "Fan Switch"
    id: fan_switch
    on_turn_on:
      - lambda: 'id(fauxmo_component).set_device_state("Bedroom Fan", true);'
    on_turn_off:
      - lambda: 'id(fauxmo_component).set_device_state("Bedroom Fan", false);'
